apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-tunnel-secrets
    namespace: cloudflared
spec:
    suspend: false
    secretTemplates:
        - name: cloudflared-tunnel-secrets
          stringData:
            cert.pem: ENC[AES256_GCM,data:P0uMQ3yeRDzkUmqJGXT5wMt/YzTiFvutCZ11x51D9oPy9gBuHAqEl7RRu12x5O/wg3z84eHVfk+W3l2XQ+A/XEptwvDangrQ60bzi/p05M7v4KcPATo/EuqiCCK2HM6RQNlQHzldmHBBMKNFIEmZTfyVop8RctWhCmPFXoKlUwruOBMsfOPWNyVZkR71tLWEv4E26u4riPZ+8UnnS1jSs57kdCz2mPkCwVASm7cBsZi1N8ayYHRvaExXpc2Mmuh1cX2mVQ4oVh5+1AjXSIcyj82m0rkMLQ1++ZFlX0ynIG+oEwiBr3vyhxjzaBcvDS1X8d231QM+DPuVIeyCZhKFd4lYBmD2fqfAE/8=,iv:BciDM03EWitSA6jwMFVqGs2jYsdx6GGChrUVT4rQjZw=,tag:vucXs7yWdTm6lICgLjjqVw==,type:str]
            credentials.json: ENC[AES256_GCM,data:j35xzgBghYaffSmquPVxrCBgpY8yYE4aim3OJt3kZtwLJZj59+N/ih99eAXyJCShd3T23WGaa+8oIwnxQcxjXRtlsd/HNvVrUlXiIgwpdJZ//2EgWSenMuvFmizmC/HKgcC8od7s2gJXXdlBvoGymBrrlS74OqGdMoDnEOeGRsyDOoV2+RGloBPes1tRmZyaBQvCJdWmtEb1sE4ex6HdKU75xTgcgX6BBQEBKCxs0Ts=,iv:Rn8IRlpTTE/S3KblN7Tc5UT4ltlwaRS9YpMunnTWYC4=,tag:N7rWWMqCuZ/2g0hEvstklA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqkt694pps8jf408tmn8gg6692mpvh23nw9jvqsfxayy9fjth9msps9fcu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXBxMytWaFFKbGwyQ3Zn
            dkt3TUgrQW9HYU5HcTBVNUpmYi9BVWNPdXpVCkxpc2JQcThHdGFLZ1V3bmlpQnc2
            SlliVUJlaDkwaGtPM1NaUjRvK1lqeE0KLS0tIFhTekV3NG9VL2RSZEJqUVdCZ3dl
            Tk04djdaU093ZnIxSGdUMENUZmFrTkEKpuGtfebfVPlugZGvDnS39mM3R8ArF3TR
            7w1N2qFzz0TmvZE6Hh+iuKketVR71ONxORlxdcAy3IzmLXHidHIS+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T08:36:36Z"
    mac: ENC[AES256_GCM,data:gkXKTCKJcZYxqyPHHZ++aw9oiUm0IVckGErVhCDhp/y9+z67nl9zY+4lW4EPn1tURyCHDV5CN9Ajxb74zGaBW+/cYC83y6WjNmdcnGX6QhYEe3fKSnLxesFbCG4eCYN/rqVbhJ1pLqBPxJGxQQQUfjof1qW71Qbknke5A/T8L0s=,iv:IGM9Z/ZrVhY230vI5kRETYtBV38htLY+6pwmRFR3Hug=,tag:Qu9FnuN8j16lVwmUXp1Rsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
