apiVersion: v1
kind: Namespace
metadata:
  name: net-tools
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: net-tools
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command:
      - sleep
      - "3600"
    securityContext:
      runAsUser: 0
  restartPolicy: Never
