apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-lan-smarthome
spec:
  ca:
    secretName: smarthome-root-ca

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: brandonhowlett.unraid@gmail.com
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token