apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-root-to-dashboard
  namespace: traefik
spec:
  redirectRegex:
    regex: ^https://traefik\.smart\.home/?$
    replacement: https://traefik.smart.home/dashboard/
    permanent: true
    
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-internal
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.smart.home`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
    - match: Host(`traefik.smart.home`) && Path(`/`)
      kind: Rule
      middlewares:
        - name: redirect-root-to-dashboard
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-internal-tls
    # secretName: smarthome-wildcard-tls